Giskard-AI/giskard

frontend/src/views/main/Main.vue
<a name="start-webappio-do-not-edit-between-tags"></a>
<div>
<a href="https://webapp.io/Giskard-AI?utm_source=pr-logo"><img src="https://webapp.io/static/logo/logodarkwithtext.svg" width="auto" height="15px" alt=""/></a>
<a href="https://webapp.io/Giskard-AI?utm_source=pr-finish-installation"><b>Finish webapp.io installation</b></a>
<a href="https://webapp.io/docs"><b>Read docs</b></a>
</div>
<hr>
<a href="https://webapp.io/Giskard-AI?utm_source=pr-screenshot"><img alt="Screenshot of main page" align="right" height="175px" width="175px" src="https://i.imgur.com/nseGEwE.png"/></a>
<h3>webapp.io steps</h3>
<a href="https://webapp.io/Giskard-AI?utm_source=pr-backend-build"><img src="https://webapp.io/static/images/check-circle-crop.png" width="17px"> Backend build</a>
<a …
=> Rename Admin button to Settings

giskard-frontend/src/views/main/project/Inspector.vue, giskard-frontend/src/views/main/project/TextExplanation.vue
Hide shap when only one feature
=> GSK-127 Remove Shap when we only have one text feature

giskard-server/src/main/java/ai/giskard/service/ProjectService.java, giskard-server/src/test/java/ai/giskard/web/rest/project/AdminProjectControllerIT.java
Change validation pattern to comply with the automatic generated key.
Closes #96
=> project key : fix incompatible check with generated key from project name

giskard-frontend/src/views/main/project/Datasets.vue, giskard-frontend/src/views/main/project/Models.vue
https://giskard.youtrack.cloud/issue/GSK-187
=> Task/gsk 187 add link to upload UI

scripts/infrastructure/giskard-docker-start.service, scripts/infrastructure/setup-docker-aws.sh
For the creation of AWS AMIs, fixed service and added a docker installation script
=> Script and service for AMI creation

.vscode/settings.json, giskard-frontend/src/views/main/project/ProjectsHome.vue
=> Add project key display on projects page

giskard-frontend/src/views/main/project/Datasets.vue
=> Remove dataset ui upload

giskard-demo-notebook/notebook/Email Classification Model - single text feature.ipynb, giskard-frontend/src/views/main/project/Inspector.vue
=> Disable SHAP for a single feature

giskard-demo-notebook/notebook/Email Classification Model.ipynb
- [x ] 🥂 Improvement (non-breaking change which improves an existing feature)
- [ x] I've read the [`CODE_OF_CONDUCT.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CODE_OF_CONDUCT.md) document.
- [ x] I've read the [`CONTRIBUTING.md`](https://github.com/Giskard-AI/ai-inspector/blob/master/CONTRIBUTING.md) guide.
=> GSK-268 added more comments to improve user experience

giskard-server/src/main/resources/aitest/code_test_templates/data_drift.yml
- [ x] 🥂 Improvement (non-breaking change which improves an existing feature)
=> GSK-312 Switch from "expected" to "reference" in data_drift.yml

giskard-server/src/main/resources/aitest/code_test_templates/metamorphic.yml
Implementing the metamorphic t-tests from citibeats.
Linked to PR https://github.com/Giskard-AI/giskard-client/pull/26
=> updated metamorphic.yml

frontend/src/utils.ts, frontend/src/views/main/project/ProjectsHome.vue
#588 
#432 - ProjectsHome.vue migration
=> Use underscores instead of dashes in auto generated project slugs

frontend/docs/vue2-vue3-migration.md, frontend/src/views/main/project/InspectorLauncher.vue
#432 => InspectorLauncher.vue migrated
=> #597 - Change loading to indefinite progress bar for Inspector Launcher

.github/workflows/check-safe-to-build.yml
Whitelist organization members for PR build sonar
N/A
=> Whitelist organization members for PR build sonar

backend/src/main/java/ai/giskard/security/SecurityUtils.java, backend/src/main/java/ai/giskard/service/DatasetService.java, backend/src/main/java/ai/giskard/web/rest/controllers/DatasetsController.java, backend/src/main/java/ai/giskard/web/rest/controllers/ModelController.java, frontend/src/api.ts, frontend/src/components/InlineEditText.vue, frontend/src/views/main/project/Datasets.vue, frontend/src/views/main/project/Models.vue, frontend/src/views/main/project/modals/DeleteModal.vue
Added the possibility to rename dataset and models for admin and project owner
Migration of component (https://github.com/Giskard-AI/giskard/issues/432):
- Models.vue
- Datasets.vue
=> 497 need to be able to rename datasets and models from the UI

README.md, python-client/giskard/cli.py, python-client/giskard/cli_utils.py
Added logs command to giskard worker
Option -n to select last n lines
Option -f to follow the logs
Documentation update of https://docs.giskard.ai/start/guides/installation/ml-worker page have been submitted
#643
=> 643 giskard worker logs

backend/src/main/java/ai/giskard/web/rest/controllers/FeedbackController.java, backend/src/test/java/ai/giskard/mock/FeedbackMock.java, backend/src/test/java/ai/giskard/mock/MockUser.java, backend/src/test/java/ai/giskard/mock/ProjectMock.java, backend/src/test/java/ai/giskard/web/rest/FeedbackControllerIT.java, backend/src/test/java/ai/giskard/web/rest/WithMockGiskardUser.java, frontend/package-lock.json, frontend/package.json, frontend/src/App.vue, frontend/src/api.ts, frontend/src/main.ts, frontend/src/views/main/project/FeedbackDetail.vue, frontend/src/views/main/project/FeedbackList.vue, frontend/src/views/main/project/modals/ConfirmModal.vue
Added possibility to delete feedback in the feedbacks list view
N/A
=> 487 option to delete feedbacks

frontend/src/views/main/project/FeedbackList.vue
Fixed issue that prevented to reopen feedback detail modal after pressing escape
=> Fixed issue that prevented to reopen feedback detail modal after pressing escape

frontend/src/components/slice/SliceDropdown.vue
Title is self descriptive
Changed "Try on" to "Validate with"
Changed "Play" button to "Validate" text button
Added toast when validation is successful
=> Improve slice validation message

backend/src/test/java/ai/giskard/web/rest/testing/TestControllerIT.java, frontend/package-lock.json, frontend/src/views/main/admin/settings/SettingsGeneral.vue
Fixed issue where selected tab was not highlighted by default
=> Fixed issue where selected tab was not highlighted by default

backend/build.gradle.kts, backend/src/main/java/ai/giskard/domain/ml/Slice.java, backend/src/main/java/ai/giskard/service/SliceService.java, backend/src/main/java/ai/giskard/service/ml/MLWorkerService.java, backend/src/main/resources/config/liquibase/changelog/20230213090159_changelog.xml, backend/src/main/resources/config/liquibase/master.xml, frontend/src/components/slice/SliceDropdown.vue, frontend/src/views/main/project/InspectorWrapper.vue
=> Various feedback for slicing

python-client/giskard/ml_worker/server/ml_worker_service.py
According to #403 embedded link to the documentation was outdated. This PR fix the issue with the suggest approach available in the issue description.
close #403
=> Fix doc link

python-client/giskard/ml_worker/server/ml_worker_service.py
Following a report by JM, it turns out slice filtering was broken.
The issue was caused by a linter suggestion that changed "==" to "is", breaking the check. To remedy this, we used a more standard way of filtering a DataFrame from a Series.
Also added a wrapper around the filter function to make sure it returns boolean-like values (so anything truthy or falsy)
=> Fix slice filtering and make it more lenient towards non-boolean types

README.md, backend/src/main/docker/grafana/provisioning/dashboards/JVM.json, backend/src/main/java/ai/giskard/service/TestService.java, backend/src/main/java/ai/giskard/web/rest/controllers/InspectionController.java, python-client/CONTRIBUTING.md, python-client/giskard/client/giskard_client.py, python-client/giskard/ml_worker/core/model_explanation.py
Fix typos across codebase.
N/A
=> chore(typos): fix typos across codebase

frontend/src/views/main/profile/UserProfileEditPassword.vue
Restore a missing import to show the Save button for password change.
=> [GSK-861] Fix 'save' button not displaying for password change

backend/src/main/java/ai/giskard/service/ee/KeygenLicenseReader.java, backend/src/main/java/ai/giskard/service/ee/License.java, backend/src/main/java/ai/giskard/web/dto/config/LicenseDTO.java, backend/src/main/java/ai/giskard/web/rest/controllers/SettingsController.java, frontend/src/generated-sources/ai/giskard/web/dto/config/license-dto.ts, frontend/src/stores/main.ts
=> Add LicenseID in Mixpanel

frontend/src/router.ts, frontend/src/views/main/project/Debugger.vue, frontend/src/views/main/project/InspectorLauncher.vue, frontend/src/views/main/project/InspectorWrapper.vue
This PR implements two things:
1. Bug fix: Fix navigation between data points using arrow keys. It was not working after creating the Debugger tab.
2. Improvement: Create a nested route for each Debugging session, so if the user refreshes their browser, they can return to the same session.
[GSK-1010 (available on Linear)](https://linear.app/giskard/issue/GSK-1010/debugger-tab-improvements)
=> [GSK-1010] Improvements in Debugger component

python-client/giskard/push/__init__.py, python-client/giskard/push/contribution.py, python-client/giskard/push/perturbation.py, python-client/tests/test_push.py
1. Refactoring perturbation push code:
- Added NumericPush and TextPush classes
- Perturbation class
2. Added Text push feature
=> Perturbation refactoring

python-client/giskard/datasets/base/__init__.py
Fixed issues with multiple column names
=> Fixed issues with multiple column names

frontend/src/views/main/admin/settings/SettingsGeneral.vue, frontend/src/views/main/project/Datasets.vue, frontend/src/views/main/project/Models.vue, frontend/src/views/main/project/Project.vue, frontend/src/views/main/project/modals/ExportTestModal.vue, frontend/src/views/main/project/modals/UploadArtifactModal.vue
This PR aims to update the documentation links and also the code snippets within the frontend files.
[GSK-1171 (available on Linear)](https://linear.app/giskard/issue/GSK-1171/update-links-and-code-snippets)
=> [GSK-1171] Update links and code snippets

python-client/giskard/scanner/performance/metrics.py, python-client/giskard/testing/tests/performance.py, python-client/giskard/utils/analytics_collector.py, python-client/tests/test_performance.py
Fixing AUC score according to the doc in the binary case: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html
=> fixed auc metric

python-client/giskard/commands/cli_server.py, python-client/giskard/ml_worker/bridge/ml_worker_bridge.py, python-client/giskard/ml_worker/utils/logging.py, python-client/pdm.lock, python-client/pyproject.toml
Adds a small command that uses ngrok to make using Giskard Server easier with Colab
=> Add Giskard server expose command

frontend/src/utils/tests.utils.ts, frontend/src/views/main/project/TestSuiteCompareExecutions.vue, frontend/src/views/main/project/TestSuiteExecutionOverview.vue
Added search on comparison screen
=> Test search doesn't work when comparing test results

python-client/giskard/ml_worker/server/ml_worker_service.py
Fix prediction and explanation from AI debug when classification label is int/float:
=> GSK-1246 - Feature/gsk 1240 manual testing issue debugger

frontend/src/views/main/project/TestSuiteExecutions.vue
Fixed text suite executions responsiveness
=> Fixed text suite executions responsiveness

.gitattributes
This will fix the language stats
=> Mark documentation dir in gitattributes

Dockerfile
Fixed postgresql 13 installation in docker image to avoid issue when the version is being bumped automatically
=> Fixed postgres 13 installation

CONTRIBUTING.md
=> rectified a spelling mistake in CONTRIBUTING.md file

python-client/giskard/core/core.py
Removed pickle tag since everything is a pickle by default 
For `NoCodeQueryFunction` we actually only save a `yaml` file representing the metadata but I think it's fine because its a very technical tag
=> Removed pickle tag since everything is a pickle by default

frontend/src/views/main/project/PredictionResults.vue
Fixed issue where prediction is not being updated on input value change
=> Fixed issue where prediction is not being updated on input value change

README.md, python-client/docs/getting-started/index.md
Small doc polish: Why Giskard + emojis in the README
=> Small doc polish: Why Giskard + emojis in the README

python-client/giskard/core/suite.py, python-client/giskard/ml_worker/server/ml_worker_service.py, python-client/tests/test_metamorphic_direction.py, python-client/tests/test_suite.py
Fixed issue with variable scope overriding suite result
=> Fixed issue with variable scope overriding suite result

python-client/giskard/datasets/base/__init__.py, python-client/giskard/scanner/result.py
Added wand dataset log. Sorry for the additional changes due to indents, these are due to idea code refactoring..
=> Added new method to the Dataset class to log dataset to the WandB run.

python-client/giskard/ml_worker/testing/registry/giskard_test.py
=> [GSK-1549] fixed bug related to test execution

python-client/giskard/ml_worker/websocket/listener.py
=> [GSK-1562] Add MixPanel tracking for Python WebSocket MLWorker actions

.github/workflows/nightly-test.yml
=> [GSK-1643] Add a step in nightly test to run integration test with testcontainer

.run/Frontend.run.xml, python-client/giskard/push/contribution.py, python-client/giskard/push/utils.py, python-client/tests/test_push.py
Reducing bounds for push contribution (numerical feat) to -/+ 5%
=> [GSK-1633] Reducing bounds for push contribution (numerical feat)

python-client/giskard/visualization/templates/suite_results/_suite_results_cards.html
Fixed suite test template passed test color issue
=> Fixed suite test template passed test color issue

python-client/giskard/push/contribution.py, python-client/pyproject.toml
appending `tool.setuptools.package-data` with `.md`
=> [GSK-1710] Added md suffix in pyproject

.github/CODEOWNERS
=> Adding CODEOWNERS file to secure .github folder

.github/workflows/build_backend.yml, .github/workflows/clear-cache.yml, .github/workflows/nightly-test.yml
Closes #GSK-1774
Example nightly run here https://github.com/Giskard-AI/giskard/actions/runs/6262665451
=> Disable cache on nightly and clear cache every week

.github/workflows/build-images.yml, .github/workflows/build_backend.yml
Fixing docker build (and python wheel upload) on main, to have an "edge" version
Passing build : https://github.com/Giskard-AI/giskard/actions/runs/6341601339
=> Fix docker build

giskard/core/suite.py
This PR fixes an error that occurs when trying to download a Test suite generated by scan.
[GSK-1837 (available on Linear)](https://linear.app/giskard/issue/GSK-1837/error-while-trying-to-download-test-suite) / [GSK-1850 (available on Linear)](https://linear.app/giskard/issue/GSK-1850/import-is-not-working)
=> [GSK-1837] Error while trying to download Test Suite

giskard/ml_worker/websocket/listener.py
Fixed transformations application from debugger
=> Fixed transformations application from debugger

giskard/ml_worker/websocket/listener.py
This fixes a lot of issues with the various actions from the push feature
=> GSK-1843 Fix push object upload

.github/workflows/sonar.yml, sonar-project.properties
=> Activate again Sonar on the python code

giskard/client/dtos.py, giskard/core/core.py, giskard/core/suite.py
Added `function_inputs` to `TestSuiteDTO`
=> Added `function_inputs` to `TestSuiteDTO`

giskard/visualization/templates/scan_report/markdown/github.md
adding newline for gh md template (tested locally)
=> Updating gh md template

giskard/core/suite.py, giskard/datasets/base/__init__.py, giskard/integrations/wandb/wandb_utils.py, giskard/models/shap_result.py, giskard/scanner/report.py
=> [GSK-1996] Fixing giskard import

giskard/core/core.py, giskard/ml_worker/testing/utils.py, giskard/ml_worker/websocket/listener.py, giskard/ml_worker/websocket/utils.py, giskard/testing/tests/performance.py, giskard/utils/artifacts.py, tests/communications/test_listener_utils.py
=> [GSK-2032] Fix debug master

giskard/core/suite.py, tests/test_programmatic.py
Removed overwriting of fixed test input from runtime test-suite args.
=> [GSK-2045] issue with fixed test inputs

giskard/core/suite.py, giskard/ml_worker/websocket/listener.py
=> [GSK-2036] Fix debug

giskard/client/dtos.py
=> [GSK-2055] Add unused field for coherence

.github/workflows/build-python.yml
=> Fix typo & copy paste in build file

giskard/core/validation.py, tests/core/test_validation.py
=> [GSK-2057] Disable finite number enforcing

tests/scan/llm/test_requirement_based_detectors.py
=> Fix back mock

giskard/testing/tests/llm/injections.py
related to https://github.com/Giskard-AI/giskard/pull/1552
=> [GSK-2060] extra debug check missing

.github/workflows/build-python.yml, tests/conftest.py
=> Try to import lightbgm first

giskard/__init__.py, giskard/ml_worker/websocket/__init__.py
=> [GSK-1952] Remove warnings from pydantic

giskard/ml_worker/websocket/listener.py
=> Fix typo in perturbation push CTA

giskard/ml_worker/utils/network.py
=> Add a timeout when trying to reach pipy

docs/knowledge/how_does_scan_work.rst, docs/knowledge/llm_vulnerabilities/index.rst
Fixed links to papers in the docs.
=> Fix references in docs

docs/reference/index.rst, docs/reference/suite/index.rst, giskard/core/suite.py
=> Fix documentation by adding Suite to index

docs/integrations/cicd/index.md, docs/integrations/dagshub/index.md, docs/integrations/mlflow/index.md, docs/integrations/mlflow/mlflow-llm-example.ipynb, docs/integrations/wandb/index.md
mainly MLflow updates. Took most of JM comments and Sagar's feedback about this page.
=> [GSK-1747] doc updates

docs/integrations/dagshub/index.md
mlflow.evaluate() related arg in DagsHub page.
=> missing argument in doc snippet

docs/getting_started/index.md
=> Docs fix images

.github/workflows/build-python.yml, pyproject.toml, tests/models/langchain/test_qa_retreiver.py, tests/scan/test_scanner.py, tests/scan/test_text_perturbation_detector.py, tests/test_worker_pool.py
=> Fix test and make it faster

giskard/scanner/scanner.py
Adds detectors names and number consumed tokens to telemetry. Will help us to optimize API costs estimation.
https://eu.mixpanel.com/project/2745644/view/3281468/app/profile#distinct_id=41502368c3be52ce
=> Track number of LLM calls/tokens in scan

giskard/commands/cli_worker.py, pdm.lock
=> Fix lockfile

docs/reference/scan/llm_detectors.rst, giskard/scanner/llm/llm_basic_sycophancy_detector.py, giskard/scanner/llm/llm_harmful_content_detector.py, giskard/scanner/llm/llm_implausible_output_detector.py, giskard/scanner/llm/llm_information_disclosure_detector.py, giskard/scanner/llm/llm_output_formatting_detector.py, giskard/scanner/llm/llm_stereotypes_detector.py
This PR updates the documentation of LLM detectors, doing two things:
- Adding docs for Sycophancy detector
- Adding a GPT-4 disclaimer to assisted detectors
[GSK-2188 (available on Linear)](https://linear.app/giskard/issue/GSK-2188/update-documentation-of-llm-detectors)
=> [GSK-2188] Update documentation of LLM detectors

pdm.lock, pyproject.toml
=> Remove protobuf

docs/open_source/scan/advanced_scan/index.rst, docs/open_source/scan/index.md
Added docs to describe how to customize scan at runtime via `params`, `features`, and `only` arguments.
=> Add docs for advanced scan usage

giskard/testing/tests/llm/__init__.py, giskard/testing/tests/llm/ground_truth.py, tests/testing/test_llm_ground_truth.py
Added `test_llm_ground_truth_similarity` and `test_llm_ground_truth`
=> Added test_llm_ground_truth_similarity

giskard/push/__init__.py
=> GSK-2080 Fix wording

.github/workflows/build-python.yml
=> Fix CI (breaking because of pdm and windows-2019)

giskard/demo/llm_ipcc_climate_change.py
Needed for https://github.com/Giskard-AI/giskard-hub/pull/301
=> Add ipcc model and dataset creation for e2e tests

README.md
=> Fix run start instructions

giskard/llm/talk/config.py, giskard/llm/talk/tools.py, giskard/models/base/model.py
In this branch my aim is to implement the "PredictFromDatasetTool", which is the first part of the "Talk to my model initiative".
=> Implementation of the "PredictFromDatasetTool"

.github/workflows/do-release.yml
=> Add slack message on release

giskard/ml_worker/websocket/__init__.py, giskard/ml_worker/websocket/utils.py, tests/communications/fixtures/with_alias.json, tests/communications/test_dto_serialization.py
Add metric_name in DTOs so it's properly sent to the backend
Related to hub PR with same issue id
=> [GSK-2406] Metric name is not shown in the Hub

giskard/testing/tests/llm/ground_truth.py, tests/testing/test_llm_ground_truth.py
=> Updated ground truth tests to have new test details

giskard/registry/slicing_function.py
=> Fixed import of Query, QueryBasedSliceFunction

.github/workflows/build-python.yml, giskard/testing/tests/data_quality.py
Remove the warning about docstring not properly done (converted to numpy)
=> Fix the docstring

docs/knowledge/catalogs/test-catalog/text_generation/index.rst, docs/reference/tests/llm.rst, giskard/testing/tests/llm/__init__.py
=> updating tests catalog

giskard/models/automodel.py, giskard/models/base/model.py, tests/models/automodel/test_loading.py
load method now uses load_model from the custom model class
=> [GSK-2311] Fixed load method 

.github/workflows/pre-commit-checks.yml
=> Skip gg shield in CI

docs/knowledge/catalogs/test-catalog/text_generation/index.rst, docs/reference/tests/llm.rst, giskard/llm/evaluators/requirements.py, giskard/testing/tests/llm/__init__.py, giskard/testing/tests/llm/ground_truth.py
Added LLM as a judge ground truth test
=> GSK-2684 Added LLM as a judge ground truth test

.github/workflows/build-python.yml
venv upload is taking 9min, deps installation is taking 3min. Cache is inefficient and making us lose time
=> Remove cache in CI

.github/workflows/build-python.yml, .github/workflows/do-release.yml, .github/workflows/lock-deps.yml, .github/workflows/post-release.yml
=> Update deps batch

docs/open_source/scan/scan_llm/index.md, docs/open_source/scan/scan_nlp/index.md, docs/open_source/scan/scan_tabular/index.md, docs/open_source/testset_generation/index.md
Updated the documentation of the scan and the RAG toolset according to @jmsquare comments.
=> [GSK-2846] Update RAG toolset and scan documentation

giskard/ml_worker/websocket/__init__.py, tests/communications/fixtures/with_alias.json
=> Fix serialisation issue with object return from llm

giskard/visualization/templates/scan_report/markdown/huggingface.md
Add markdown comments to separate  examples
=> [Gsk-2864] fragment markdown report

giskard/llm/loaders/prompt_injections.py, tests/scan/llm/test_prompt_injection_detector.py
Resolved in https://github.com/Giskard-AI/prompt-injections/commit/ce50a549dadc46b48c931250d2dd71d5f003c0c2
=> [GSK-2793] Updated injection prompts (removing duplicates)

giskard/llm/talk/config.py, giskard/llm/talk/tools/metric.py
Fixed bug, preventing from metrics calculation with initial data pre-filtering.
=> Fixed metric calculation bug.

tests/utils.py
=> Fix download link for enron

giskard/functions/transformation.py
push was failing as the perturbation was changing the dtype of one of the columns, and the model prediction breaks
=> hot-fixing transformation in push perturbation

giskard/visualization/templates/rag_report/rag_report.html
Remove an hardcoded placeholder for the correctness value inside the RAGET template.
=> Fix RAGET correctness value

docs/open_source/setting_up/index.md, docs/open_source/testset_generation/testset_generation/index.md
Added instruction in:
- `Setting up the LLM Client` page
- `RAGET Testset Generation` page
=> Propagate bedrock instruction into other pages

giskard/llm/evaluators/coherency.py
Fixed typo in coherency.py
None
modified)
=> Fixed typo in coherency.py

docs/open_source/scan/scan_llm/first.md, docs/open_source/setting_up/index.md, docs/open_source/testset_generation/testset_generation/index.md
Added embedding instructions for bedrock client
=> Added embedding instructions for bedrock client

README.md
This PR adds a link to `giskard-vision` repo.
[GSK-3639 (available on Linear)](https://linear.app/giskard/issue/GSK-3639/rename-policies-and-compliance)
=> Add giskard-vision link to README

pyproject.toml
Added prompt injection datasets to packaged data
=> Added prompt injection datasets to packaged data

docs/open_source/scan/scan_llm/index.md
Fixed broken link [to "Setting up the LLM Client" documentation page](https://docs.giskard.ai/en/stable/open_source/setting_up/) from [the "LLM scan" documentation page](https://docs.giskard.ai/en/stable/open_source/setting_up/index.html)
=> Fixed broken link to "Setting up the LLM Client" documentation page

giskard/llm/client/gemini.py
Wrong role was returned in the formatted message of the GeminiClient making the scan failing
=> Fixed gemini role issue

giskard/llm/client/gemini.py, tests/llm/test_llm_client.py
Fixed token count on Gemini client
modified)
=> Fixed token count on Gemini client

package-lock.json, package.json
Batch dependency upgrade
#1993 
#1973 
#1972 
#1971 
#1970
=> Batch dependency upgrade

README.md
=> Add sponsors to README, remove Sonar badge

giskard/scanner/calibration/overconfidence_detector.py, giskard/scanner/calibration/underconfidence_detector.py, giskard/scanner/correlation/spurious_correlation_detector.py, giskard/scanner/data_leakage/data_leakage_detector.py, giskard/scanner/llm/llm_basic_sycophancy_detector.py, giskard/scanner/llm/llm_chars_injection_detector.py, giskard/scanner/llm/llm_faithfulness_detector.py, giskard/scanner/llm/llm_harmful_content_detector.py, giskard/scanner/llm/llm_implausible_output_detector.py, giskard/scanner/llm/llm_information_disclosure_detector.py, giskard/scanner/llm/llm_output_formatting_detector.py, giskard/scanner/llm/llm_prompt_injection_detector.py, giskard/scanner/llm/llm_stereotypes_detector.py, giskard/scanner/performance/performance_bias_detector.py, giskard/scanner/robustness/ethical_bias_detector.py, giskard/scanner/robustness/text_perturbation_detector.py, giskard/scanner/stochasticity/stochasticity_detector.py
=> Added documentation on which tag to use when using the scan's `only` param for each detector

docs/reference/notebooks/LLM_QA_IPCC.ipynb, docs/reference/notebooks/LLM_QA_Winter_Olympics.ipynb, pdm.lock
This PR removes deprecated links from test suite results widget
=> Update test suite result on LLM QA notebooks

.github/workflows/build-python.yml, package-lock.json, package.json
Batch of upgrades from Dependa bot PRs.
#2044 
#2064 
#2065 
#2066 
#2067 
#2068
=> Dependa bot - batch upgrade 2024-11-18

docs/getting_started/index.md
=> chore: update getting started docs

.github/workflows/build-python.yml, package-lock.json, package.json
=> chore(deps): batch upgrade 2025-03

pdm.lock, pyproject.toml
I updated faiss-cpu.
modified)
=> chore(deps): update package `faiss-cpu` version
