frontend/package-lock.json, frontend/package.json, frontend/src/views/main/project/InspectorWrapper.vue
[GSK-67](https://giskard.youtrack.cloud/issue/GSK-67) Give keyboard shortcuts for next and previous
=> GSK-67 Give keyboard shortcuts for next and previous

giskard-common/proto/ml-worker.proto, giskard-frontend/src/views/main/project/PredictionExplanations.vue, giskard-ml-worker/ml_worker/core/model_explanation.py, giskard-ml-worker/ml_worker/server/ml_worker_service.py, giskard-server/src/main/java/ai/giskard/service/InitService.java, giskard-server/src/main/java/ai/giskard/web/rest/controllers/ModelController.java
fix regression by sending the same class of messages from ml worker
=> Fix regression

giskard-frontend/src/views/main/project/PredictionResults.vue
Solve this by taking the top N predictions and aggregate the others into a new option. 
N is fixed to 10.
=> GSK-42 First prediction label is empty

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
This allows to have a prebuilt codespace environment for browser-based IDE.
Bonus: This builds and deploy transient preview environments automatically, like webapp.io!
=> Configure devcontainer for codespaces setup

docker-compose.ami.yml, scripts/infrastructure/giskard-docker-start.service
Infrastructure changes to create AMIs on AWS and ideally automate their creation based on release tags
=> AWS AMI creation

giskard-ml-worker/ml_worker/utils/grpc_mapper.py, giskard-ml-worker/poetry.lock, giskard-ml-worker/pyproject.toml, giskard-ml-worker/test/fixtures/enron_multilabel_classification.py, giskard-ml-worker/test/test_data/enron_data.csv, giskard-ml-worker/test/test_metamorphic_direction.py, giskard-server/src/main/resources/aitest/code_test_templates/metamorphic.yml
=> Gsk 205 metamorphic test for categorical perturbation is not working

giskard-frontend/src/views/main/profile/UserProfile.vue
Change "No external ML Worker is connected" color to warning. UI nitpick.
=> Change "No external ML Worker is connected" color to warning

frontend/docs/vue2-vue3-migration.md, frontend/src/views/main/project/TextExplanation.vue
#387 
#432 => Tick TeamExplanation.vue when merged
=> #387 - Make LIME categories searchable

backend/src/main/java/ai/giskard/service/DatasetService.java
Tablesaw does not handle ranges bigger than tables so this just adds a small check. I found no other unprotected usages of inRange in our code.
=> Prevent range filter from breaking when range > table size

frontend/src/views/main/admin/settings/SettingsGeneral.vue, frontend/src/views/main/project/ProjectsHome.vue
Add a spinner and disable next button when preparing the import of a large project:
=> Add spinner when preparing import of projects

frontend/src/views/main/project/InspectorWrapper.vue
The following message is display when no data are available:
=> Clear message when a filter filters out all data

frontend/src/views/main/project/Inspector.vue
Fixed an error in the console and not allowing the disabled text tab tooltip's explaination:
=> Fixed error related to tooltip in the inspector

README.dev.md, backend/src/main/resources/config/application-dev.yml, backend/src/main/resources/config/application-preprod.yml, backend/src/test/resources/config/application.yml
This branch is meant to make a Giskard dev install work seamlessly when installing on Windows.
Here are the fixes it implements:
- Change giskard-home to be equal to `${user.home}/giskard-home` instead of `${HOME}/giskard-home` => user.home is provided by Spring and is compatible with all operating systems, HOME does not exist by default on Windows
- Add some documentation for common Python errors (working on making it happen by default instead of be in documentation at the moment....)
=> Fix Giskard dev installation on Windows (no WSL)

frontend/src/views/main/project/Inspector.vue, frontend/src/views/main/project/PredictionExplanations.vue, frontend/src/views/main/project/PredictionResults.vue
This improvement aims to solve the problem when a user edits a feature value in the Inspector table.
1. Many requests were sent to the backend during this user interaction, so we're doubling the debounce time to alleviate that. 
2. Also, now we ensure that the PredictionResults and PredictionExplanations cards will always be requested at the same time, creating a single variable of debounce time to be used by both components.
[Increase debounce timeout in Inspector (via Linear)](https://linear.app/giskard/issue/GSK-829/increase-debounce-timeout-in-inspector)
=> [GSK-829] Increase debounce timeout in Inspector

python-client/giskard/models/base/__init__.py, python-client/giskard/models/utils.py
Solves the `Object of type int64 is not JSON serializable` issue mainly encountered in `sklearn` and `catboost` models where `.classes_` is a numpy array.
=> task/Numpy encoder for classification_labels

frontend/src/views/main/project/PredictionResults.vue
Hides the threshold in AI debugger for non-binary classification models:
=> Hide threshold for non-binary classification models

frontend/src/views/setup/Setup.vue
This PR aims to make a small modification to the Setup page (License Management).
The idea is to ensure that the user won't submit a new form if they already have a license file.
[GSK-1114 (available on Linear)](https://linear.app/giskard/issue/GSK-1114/license-management)
=> Update License Management screen

frontend/src/views/main/project/Datasets.vue, frontend/src/views/main/project/Models.vue
This PR brings the code that changes the type of notification when loading artifacts (Datasets or Models).
Instead of the blue card notification, we have a Loading fullscreen in place of artifact lists.
[GSK-1027 (available on Linear)](https://linear.app/giskard/issue/GSK-1027/change-notification-when-loading-project-artifacts)
=> [GSK-1027] Change notification when loading project artifacts

frontend/src/views/main/Main.vue, frontend/src/views/main/project/Project.vue, frontend/src/views/main/project/ProjectsHome.vue
Fix all problems related to routing/tabs.
- When a Test Suite is opened, if the user clicks on "Testing" tab it should display the list of Test suites
- When a Debugging Session is opened, if the user clicks on "Debugger" tab it should display the list of Debugging sessions
- When refreshing the page with a project opened, it should keep displaying the tabs as enabled. At the moment it's displaying as disabled after refreshing.
- If a project is opened, going to Settings should keep still possible to navigate to the other tabs.
- Creating a new Debugging session from Debugger tab should redirect to this session
- Creating a new Debugging session from Catalog/Models tab should redirect to this session
- Creating a new Test suite from Testing tab should redirect to this suite.
[GSK-1194 …
=> [GSK-1194] Fix redirect issues

backend/src/main/java/ai/giskard/service/ml/MLWorkerService.java, backend/src/main/java/ai/giskard/web/rest/controllers/MLWorkerController.java, frontend/src/api.ts, frontend/src/components/AddDebuggingSessionModal.vue, frontend/src/components/StartWorkerInstructions.vue, frontend/src/stores/ml-worker.ts, frontend/src/views/main/project/Debugger.vue, frontend/src/views/main/project/InspectorLauncher.vue
This PR aims to add an endpoint to check if an external ML Worker is connected. 
This endpoint will be useful in deciding whether display some functionality on the frontend.
At the moment, three components are using this endpoint:
- Debugger.vue
- AddDebuggingSessionModal.vue
- InspectorLauncher.vue
In the future, more components will be using this endpoint.
[GSK-1099 (available on Linear)](https://linear.app/giskard/issue/GSK-1099/disable-actions-that-require-external-worker-if-no-worker-is-connected)
=> [GSK-1099] Disable components when no ML Worker connected

python-client/giskard/scanner/llm/toxicity_detector.py
ToxicityDetector is running two checks: first toxicity of simple generated text, second toxicity with DAN prompt. In the second case, it runs text generation on the whole dataset!
Instead, it should always use a small sample.
=> ToxicityDetector runs DAN prompt on whole dataset

frontend/src/views/main/project/Catalog.vue, frontend/src/views/main/project/FiltersCatalog.vue, frontend/src/views/main/project/InspectorLauncher.vue, frontend/src/views/main/project/TestsCatalog.vue, frontend/src/views/main/project/TransformationsCatalog.vue, frontend/src/views/main/project/modals/AddTestToSuite.vue
This PR adds telemetry to actions on the Catalog tab.
[GSK-1203 (available on Linear)](https://linear.app/giskard/issue/GSK-1203/track-interactions-on-catalog-with-mixpanel)
=> [GSK-1203] Track interactions on Catalog with mixpanel

python-client/giskard/models/base/__init__.py
fixes: https://linear.app/giskard/issue/GSK-1098/modelupload-returns-none-instead-of-model-id
I see no reason why we can't just at least symmetrise the output of upload between `Dataset` and `Model`.
The symmetrisation of the constructor (Dataset takes id as arg of __init__ while Model doesn't) can be dealt with later.
=> return id after upload of model

frontend/src/views/main/project/PredictionExplanations.vue, frontend/src/views/main/project/PredictionResults.vue, frontend/src/views/main/project/TextExplanation.vue
This PR aims to add a spinner to be shown while the explanation is being computed.
[GSK-1236 (available on Linear)](https://linear.app/giskard/issue/GSK-1236/add-spinner-to-text-explanation-while-its-computing)
=> [GSK-1236] Add spinner to explanations while its computing

frontend/src/stores/main.ts
Only set the backend as not ready when there is an API error (no waiting for backend to try on refresh)
=> Only set the backend as not ready when there is an API error

frontend/src/views/main/project/modals/AddTestToSuite.vue, frontend/src/views/main/utils/KwargsCodeEditor.vue
This PR aims to fix the size of the component `AddTestToSuite`. There was a bug in which the user could not close the modal if the content were too big. Now, this modal is scrollable.
[GSK-1320 (available on Linear)](https://linear.app/giskard/issue/GSK-1320/no-add-test-button-when-adding-accuracy-actual-reference-difference)
=> [GSK-1320] Make AddTestToSuite scrollable

python-client/giskard/scanner/robustness/base_detector.py
The random generator `choice` method does replacement by default, resulting in duplicate indexes which then break the scan.
=> [GSK-1341] Fix bug in base text perturbation detector

python-client/giskard/scanner/result.py, python-client/giskard/scanner/templates/base.html, python-client/giskard/scanner/templates/scan_results.html
- made the scan result `to_html` produce a complete HTML page
- optional `embed=True` produces the iframe to embed in notebook
- fixed problem in the j2 templates that prevented the correct layout to be used
=> Make scan widget optionally embeddable

python-client/giskard/core/suite.py, python-client/tests/test_programmatic.py
Global argument of a test suite take priority on test argument
=> Global argument of a test suite take priority on test argument

frontend/src/views/main/admin/EditUser.vue
Fixed issue with form not being reset when switching users
=> Fixed issue with form not being reset when switching users

frontend/src/views/main/project/FiltersCatalog.vue, frontend/src/views/main/project/TransformationsCatalog.vue
This PR aims to add a spinner to Slicing and Transformation Function run buttons (Catalog tab).
[GSK-1400 (available on Linear)](https://linear.app/giskard/issue/GSK-1400/add-spinner-to-the-run-button-in-the-catalog)
=> [GSK-1400] Add spinner to the run button in the catalog

backend/src/main/java/ai/giskard/web/rest/controllers/SlicingFunctionController.java
Fixed creation of slicing function
=> Fixed creation of slicing function

python-client/giskard/models/base/wrapper.py
The saving and loading of `batch_size` should be backward compatible.
=> [GSK-1477] Ensuring backward compatibility of models

python-client/giskard/slicing/slice.py, python-client/tests/slicing/test_query_slicer.py
Fixed issue where `QueryBasedSliceFunction` wasn't working with bytes
=> Fixed issue where `QueryBasedSliceFunction` wasn't working with bytes

backend/src/main/java/ai/giskard/service/UserDeletionService.java, frontend/src/views/main/admin/AdminUsers.vue
This PR aims to fix a bug when clicking on "Restore User" button. Also, it add tooltips to all buttons on `AdminUsers.vue` table.
[GSK-1396 (available on Linear)](https://linear.app/giskard/issue/GSK-1396/restore-user-doesnt-work)
=> [GSK-1396] Restore user doesn't work

python-client/giskard/push/__init__.py
I changed `action` and `explanation` according to the linear card, but kept the button as "Create test", unit test is not really appropriate here.
=> [GSK-1491] Changing text of Create test CTA

frontend/src/views/setup/Setup.vue
This PR changes the Company name input in the license request form, making it mandatory.
[GSK-1472 (available on Linear)](https://linear.app/giskard/issue/GSK-1472/make-company-field-mandatory-on-the-license-request-form)
=> [GSK-1472] Make company field mandatory on the license request form

backend/src/main/java/ai/giskard/web/rest/controllers/TestFunctionController.java, python-client/docs/catalogs/test-catalog/classification/index.rst, python-client/docs/reference/tests/statistic.rst, python-client/giskard/scanner/correlation/spurious_correlation_detector.py, python-client/giskard/testing/__init__.py, python-client/giskard/testing/tests/statistic.py, python-client/tests/test_statistical.py
Titanic scan:
Todo: write docstrings
=> [GSK-1316, GSK-1415] Spurious Correlation tests

frontend/src/components/SuiteInputListSelector.vue, frontend/src/views/main/project/FiltersCatalog.vue, frontend/src/views/main/project/modals/CreateSliceCatalogModal.vue
This PR aims to make it possible to create a new slicing function directly from the Catalog tab.
There will be an item on the Slicing Function list called "CREATE NEW SLICING FUNCTION". 
Once clicked, it opens a modal with a form. On this form there will be radio buttons with possible scopes for a new slicing function:
1. Specific dataset: The form will fetch columns from a specific dataset selected by user, so the user can choose a column.
2. General: The form will ask for a generic string to be used as column name.
There will be **two merges** for this PR. The first one implements the "Specific dataset" scope, and the second one implements the "General" scope (because it may cause a lot of conflicts with #1175).
[GSK-1540 (available on …
=> [GSK-1540] Make it possible to create a slicing function directly from Catalog

frontend/src/views/main/utils/SlicingFunctionSelector.vue
This PR aims to make the "Create new slice" option more visible in SlicingFunctionSelector
[GSK-1541 (available on Linear)](https://linear.app/giskard/issue/GSK-1541/make-create-new-slice-option-more-visible)
=> [GSK-1541] Make "Create new slice" more visible

frontend/src/components/PushPopover.vue, python-client/giskard/push/__init__.py, python-client/giskard/utils/artifacts.py
This PR makes the push tooltip and card with a smaller width, but also displaying their contents without hidden overflow.
[GSK-1563 (available on Linear)](https://linear.app/giskard/issue/GSK-1563/push-hover-preview-is-to-long-for-text)
=> [GSK-1563] Fix tooltip size when hovering on push button

frontend/src/views/main/project/InspectionFilter.vue
This PR adds a different `background-color` to each filter button on the Debugger tab. This can help the user to identify which filter is currently applied.
[GSK-1574 (available on Linear)](https://linear.app/giskard/issue/GSK-1574/change-color-if-filter-applied)
=> [GSK-1574] Add different background color to each filter button on Debugger

frontend/src/views/main/project/InspectorWrapper.vue
This PR makes the previous data point available while the shuffle mode is on in the Dataset Explorer (Debugger tab). Previously, it was not able to move back to the previous data point when the shuffle mode was on.
[GSK-1576 (available on Linear)](https://linear.app/giskard/issue/GSK-1576/cant-go-back-in-shuffle-mode)
=> [GSK-1576] Make "go back" available with shuffle mode in Dataset Explorer

python-client/giskard/ml_worker/testing/functions/transformation.py, python-client/giskard/push/perturbation.py
Changing the perturbation of numerical features, from +/- 2*MAD, to 10%*value.
=> [GSK-1634] From MAD to 10% change per sample

python-client/giskard/core/errors.py, python-client/giskard/integrations/wandb/wandb_utils.py, python-client/giskard/models/model_explanation.py, python-client/giskard/models/shap_result.py
=> [GSK-1702] SHAP import issue

python-client/giskard/core/model_validation.py, python-client/giskard/integrations/mlflow/giskard_evaluator_utils.py, python-client/giskard/models/base/model.py, python-client/giskard/scanner/__init__.py, python-client/giskard/scanner/scanner.py
moving saving and loading validation to `model.upload()`, removing `ValidationFlags`
=> [GSK-1684] removing validation flags for model evaluation

.github/workflows/build_backend.yml
Slight improvement to not run integration tests on windows
Also avoid re-running not slow tests
=> Do not run integration tests on windows

.github/workflows/build_backend.yml, python-client/giskard/core/validation.py, python-client/giskard/llm/talk/talk.py, python-client/giskard/ml_worker/testing/registry/decorators.py, python-client/giskard/ml_worker/testing/registry/giskard_test.py, python-client/giskard/ml_worker/testing/registry/slicing_function.py, python-client/giskard/ml_worker/testing/registry/transformation_function.py, python-client/giskard/models/automodel.py, python-client/giskard/models/base/model.py, python-client/giskard/models/base/model_prediction.py, python-client/giskard/models/langchain.py, python-client/giskard/models/sklearn.py, python-client/giskard/settings.py, python-client/pdm.lock, python-client/pyproject.toml, python-client/tests/llm/test_talk.py, python-client/tests/scan/test_performance_bias_detector.py, python-client/tests/test_settings.py
Major issues encountered : 
- base settings is in a different package for pydantic v2 
- handling it with extra deps was not working, since pdm was not installing it
- since it's used only in one class, just doing the behaviour by hand
- validate_arguments was renamed validate_call in pydantic v2
- validate_call works only on types, so was creating issues to pickle code on SlicingFunction, TransformationFunction, and test decorator
- validate_call has been moved inside decorator
Everything else is only minor changes to enforce types and respect pydantic validation
=> [GSK-1745] Support both Pydantic 1 & 2

python-client/giskard/scanner/llm/gender_stereotype_detector.py
The issue was due to the nested f-string contained in the `_prompt_template` in `gender_stereotype_detector`.
=> fixed gender_stereotype_detector issue

python-client/giskard/cli_utils.py, python-client/giskard/ml_worker/ml_worker.py, python-client/giskard/ml_worker/websocket/__init__.py
- `AnyHttpUrl` API becomes read-only and arg constructor is changed;
- `AnyHttpUrl` cannot be implicitly considered as a string;
- `pydantic` v2 has more strict validations on `Optional` fields.
=> [GSK-1783] Fix issues due to pydantic compatibility migration

backend/src/main/java/ai/giskard/service/MailService.java
This PR solves a bug when a user tries to create a new feedback and a red message appears just below the modal displaying a backend error. 
Basically, the backend was trying to create a feedback without a email from, generating an uncatched exception. Therefore, I added a default email from (noreply@giskard.ai) to avoid this problem.
[GSK-1790 (available on Linear)](https://linear.app/giskard/issue/GSK-1790/feedback-button-does-not-work-in-the-demo-environment)
=> [GSK-1790] Fix UI bug when adding a new feedback

.github/workflows/clear-cache.yml, frontend/src/views/main/project/modals/AddTestToSuite.vue
Fix add test to test suite from the giskard catalog due to invalid body being sent (migrated api to openapi)
=> GSK-1797 Fix add test to test suite

backend/src/main/java/ai/giskard/exception/MLWorkerIllegalReplyException.java, python-client/giskard/ml_worker/websocket/__init__.py, python-client/giskard/ml_worker/websocket/listener.py, python-client/giskard/ml_worker/websocket/utils.py
=> [GSK-1793][GSK-1796] Fix callable functions downloading in data processing

python-client/giskard/push/perturbation.py, python-client/tests/fixtures/drug_classification__multiclass_classification.py, python-client/tests/fixtures/enron_multilabel_classification.py, python-client/tests/fixtures/fraud_detection__binary_classification.py, python-client/tests/fixtures/german_credit_scoring.py, python-client/tests/fixtures/hotel_text__regression.py, python-client/tests/fixtures/medical_transcript_multiclass_classification.py, python-client/tests/fixtures/xboost_classification.py, python-client/tests/test_push.py
=> [GSK-1711] Added check of push output

python-client/giskard/core/core.py, python-client/giskard/ml_worker/websocket/utils.py
=> Feature/gsk 1818 remove unnecessary objects in the UI

.gitattributes, .github/dependabot.yml, .github/workflows/build-python.yml, .pre-commit-config.yaml, .readthedocs.yaml, README.dev.md, README.md, docs/README.md, docs/conf.py, docs/guides/scan/index.rst, docs/tutorials/libraries/tensorflow/classification_tfhub.md
Quick fixes to repair the docs
=> Fix paths due to removal of python-client

README.md, docs/getting-started/index.md, docs/getting-started/quickstart.ipynb, docs/guides/installation_app/index.rst, docs/guides/upload/index.md
Update documentation adding on-premise message on several pages.
No.
- [ x] 📚 Examples / docs / tutorials / dependencies update
=> Update docs to add on-premise message.

giskard/commands/cli_server.py
Our `latest` image could disappear (or not on the first 10 items in Docker Hub repository), where the client will get stuck on parsing.
Use the version matching the local Giskard client in this case, and handle a few edge cases during upgrade.
=> [GSK-1813] Fix giskard server upgrade runs for 20mns without returning

.gitignore, giskard/client/giskard_client.py, giskard/commands/cli_worker.py, giskard/datasets/base/__init__.py, giskard/ml_worker/ml_worker.py, giskard/ml_worker/websocket/__init__.py, giskard/ml_worker/websocket/listener.py, giskard/ml_worker/websocket/utils.py, giskard/models/base/model.py, giskard/utils/__init__.py, pyproject.toml
=> GSK-1863 : Using multiprocess instead of threading

giskard/commands/cli_worker.py, giskard/ml_worker/websocket/listener.py, giskard/settings.py, giskard/utils/__init__.py
=> Make worker action cancellable

giskard/ml_worker/websocket/listener.py
=> [GSK-1770] Fix text explanation for  regression model

giskard/ml_worker/ml_worker.py
Fix the error when connecting using `giskard worker start -u http://<host> -k <key>`:
```
Traceback (most recent call last):
File "/Users/inoki/.virtualenvs/giskard-py310-dev/bin/giskard", line 8, in <module>
sys.exit(cli())
File "/Users/inoki/.virtualenvs/giskard-py310-dev/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/Users/inoki/.virtualenvs/giskard-py310-dev/lib/python3.10/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/Users/inoki/.virtualenvs/giskard-py310-dev/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/Users/inoki/.virtualenvs/giskard-py310-dev/lib/python3.10/site-packages/click/core.py", line 1688, in …
```
=> Use 80 as default port in ML worker

giskard/core/core.py
Added default value for clauses to match backend DTO
[GSK-1908](https://linear.app/giskard/issue/GSK-1908/titanic-demo-snippet-breaks-at-test-suite-upload)
=> Added default value for clauses to match backend DTO

giskard/utils/analytics_collector.py
=> Fix the excepthook for threads

.github/workflows/build-python.yml, README.md, giskard/testing/tests/drift.py, pdm.lock, pyproject.toml
- Removing upper bounds for pandas (default to version >2)
- Dropping python 3.8
- Updating tensorflow to latest version
- Updating default pydantic version to 2
- Adding pdm script to generate lock (handle arm64 lock not done properly)
=> Allow latest pandas version

giskard/core/suite.py
Add uploaded default params to uploaded uuid list
=> Avoid uploading default params several times

.github/workflows/build-python.yml
=> Add basic import test

.github/workflows/build-python.yml
PDM does not provide `pip` by default, so the system pip was erroneusly used. Standard library `venv` does instead add `pip` to the environment.
=> Fix `pip` CI job

giskard/ml_worker/websocket/__init__.py, tests/communications/test_dto_serialization.py
The `version` field will be created and maintained by Backend.
Failed auto tests after merging main: https://github.com/Giskard-AI/giskard/actions/runs/6702684521/job/18212031756#step:16:3646
=> Remove auto-created `version` from mandatory fields

giskard/core/core.py, giskard/testing/tests/performance.py, giskard/utils/artifacts.py
Made kwargs default value persistent in the Hub
=> [GSK-1914] Made kwargs default value persistent in the Hub

giskard/scanner/common/loss_based_detector.py, tests/fixtures/titanic.py, tests/scan/test_performance_bias_detector.py
Issues:
- the Titanic dataset in the fixtures is not initialized correctly: it is missing the categorical features, which are then considered "text"
- normally this should not be a problem because the text slicer would work equally well, creating the same slices when there are few unique values
- but by default, the vectorizer ignores words of less than 2 chars, and in this case the values are single-letter values "S", "Q", and they are ignored by the text vectorizer
The behaviour of the vectorizer makes sense. On the contrary, I fixed the fixture Dataset by putting the correct categorical features. This can possibly break other tests.
---
Side note: while checking how the slices were treated in the `LossBasedDetector`, I added an extra filter on slice size which should make the slicing …
=> [GSK-2037] Fix test for Benjamini-Hochberg filtering in PerformanceBiasDetector

giskard/client/dtos.py, giskard/core/core.py, giskard/ml_worker/core/savable.py, tests/models/test_base_model.py, tests/test_artifact_download.py, tests/test_dataset.py, tests/test_upload.py, tests/utils.py
- Separate #1504 by websocket actor and model/dataset/callable downloading.
- Improve meta info mock using the DTOs imported in #1514
- Fix optional `target` field in `DatasetMetaInfo` in GSK-1990
[GSK-1990]
[GSK-1509]
=> [GSK-1509][GSK-1990] Add up/download tests for model, dataset and callable

giskard/ml_worker/websocket/utils.py
Before, it was test function who provides the name in debug mode. We need to loose this constraint to avoid providing name everywhere.
[GSK-1906]
=> [GSK-1906] Allow output to be anonymous from ad-hoc test

docs/open_source/scan/scan_llm/index.md, docs/open_source/scan/scan_nlp/index.md, docs/open_source/scan/scan_tabular/index.md
This PR updates the [scan docs](https://docs.giskard.ai/en/latest/open_source/scan/scan_llm/index.html#upload-your-test-suite-to-the-giskard-hub-to), adding a code snippet to upload the scan results and referencing the [upload your object](https://docs.giskard.ai/en/latest/giskard_hub/upload/index.html#upload-your-object) guide.
[GSK-2111 (available on Linear)](https://linear.app/giskard/issue/GSK-2111/update-upload-scan-docs)
=> [GSK-2111] Update scan docs

giskard/ml_worker/websocket/listener.py, giskard/utils/worker_pool.py, tests/test_worker_pool.py
To make exception info consistent w/o process worker in GSK-1701.
=> [GSK-2114] Retrieve full exception info from worker process

giskard/scanner/llm/llm_chars_injection_detector.py, giskard/testing/tests/llm/injections.py, tests/testing/test_llm_chars_injector.py
- Fixing error handling in `LLMCharInjector`
- Adding tests for the testing function
- Increasing choices of `max_repetitions` to avoid OpenAI server-side filtering
- Improving handling of BERT score computation to lower memory usage (also in tests)
=> [GSK-2138,GSK-2142] Fixes to LLM special chars injection

docs/getting_started/quickstart/quickstart_llm.ipynb, docs/getting_started/quickstart/quickstart_nlp.ipynb, docs/getting_started/quickstart/quickstart_tabular.ipynb
Added instructions about how to export scan report to HTML, useful if the scan is not performed in a notebook.
=> How to export scan report in quickstarts [GSK-2151]

giskard/integrations/avid.py, giskard/models/base/model.py, tests/integrations/test_avid.py
- Fixed an issue with AVID report generation when the `Dataset` object has no name
- Same for `Model` object with no name (we take the class name)
- Added more tests
=> Exclude anonymous dataset from AVID report

README.md
Fixed Broken documentation link in readme from : `https://docs.giskard.ai/en/latest/getting-started/quickstart.html` (404 Not Found)  to `https://docs.giskard.ai/en/latest/index.html`
https://github.com/Giskard-AI/giskard/issues/1621
=> fix(Readme) : Documentation broken link #1621

giskard/scanner/__init__.py, giskard/scanner/calibration/overconfidence_detector.py, giskard/scanner/calibration/underconfidence_detector.py, giskard/scanner/common/loss_based_detector.py, giskard/scanner/correlation/spurious_correlation_detector.py, giskard/scanner/data_leakage/data_leakage_detector.py, giskard/scanner/llm/base.py, giskard/scanner/llm/llm_basic_sycophancy_detector.py, giskard/scanner/llm/llm_chars_injection_detector.py, giskard/scanner/llm/llm_faithfulness_detector.py, giskard/scanner/llm/llm_implausible_output_detector.py, giskard/scanner/llm/llm_output_formatting_detector.py, giskard/scanner/llm/llm_prompt_injection_detector.py, giskard/scanner/registry.py, giskard/scanner/robustness/base_detector.py, giskard/scanner/scanner.py, giskard/scanner/stochasticity/stochasticity_detector.py, tests/scan/llm/test_chars_injection_detector.py, tests/scan/test_detector_registry.py, tests/scan/test_overconfidence_detector.py, tests/scan/test_performance_bias_detector.py, tests/scan/test_scanner.py, tests/scan/test_spurious_correlation_detector.py, tests/scan/test_stochasticity_detector.py, tests/scan/test_text_perturbation_detector.py, tests/scan/test_underconfidence_detector.py
The Giskard scan can now be limited to an arbitrary subset of features:
```py3
import giskard as gsk
...
report = gsk.scan(model, dataset, features=["feature_1", "feature_2"])
```
=> Only scan a subset of features [GSK-2173]

giskard/slicing/text_slicer.py, tests/scan/test_slicers.py
Prevents detectors from breaking when a column declared as text contains non-textual values.
=> Cast to string in text slicer [GSK-2185]

giskard/scanner/calibration/overconfidence_detector.py, giskard/scanner/calibration/underconfidence_detector.py, giskard/scanner/common/loss_based_detector.py, giskard/scanner/performance/performance_bias_detector.py
This PR allow users to set maximum number of samples (`max_dataset_size`) in loss-based scan detectors.
=> [GSK-1953] Max data size as param

giskard/client/giskard_client.py
Fixed bug making it impossible to create giskard client
[GSK-2281](https://linear.app/giskard/issue/GSK-2281/response-object-has-no-attribute-status)
=> Fixed bug making it impossible to create giskard client

giskard/client/giskard_client.py, giskard/client/io_utils.py, tests/client/test_save_meta.py
For some reasons, there could be `numpy.bool_` in our metadata, which is not serializable by json.
Provide a customized Json encoding rule to convert it as a bool.
=> [GSK-2184] Fix error when uploading dataset with bool column

giskard/slicing/slice.py
Fixed doc format of `QueryBasedSliceFunction`
=> Fixed doc format of `QueryBasedSliceFunction`

giskard/core/core.py, giskard/scanner/robustness/text_transformations.py, giskard/slicing/slice.py, giskard/slicing/text_slicer.py
See also https://github.com/Giskard-AI/giskard-hub/pull/283
=> [GSK-2294] Fix doc for slicing and transformations

giskard/datasets/base/__init__.py
DataProcessor was doing a copy every time, event in the case of slice.
The issue is the slice was actually referencing the whole dataset, so the whole dataset was kept in memory.
Now, we only reference the existing one.
Testing on another large dataset (76020, 371), was crashing before, working now.
=> [GSK-2346] Avoid copying whole dataset when doing slicing

giskard/commands/cli_hub.py
Handle environment variable when starting hub using cli
To set env file use:
`python -m giskard.hub --env-file prod.env` 
To set env manually use:
`python -m giskard.hub --env OPENAI_API_KEY=sk-... -e ANOTHER_KEY=...` 
[GSK-2326 (available on Linear)
](https://linear.app/giskard/issue/GSK-2326/add-possibility-to-specify-db-url-and-userpassword-when-starting-the)
=> [GSK-2326] Handle environment variable when starting hub using cli

giskard/scanner/robustness/text_transformations.py, tests/scan/test_text_transformations.py
Added rng and seed args inside `TextLanguageBasedTransformation` to  fix stochastic behavior in text transformations. 
Also fixed the related tests.  
[GSK-2332]
=> Text transformations used by EthicalBiasDetector are not deterministic [GSK-2332]

giskard/scanner/performance/metrics.py, giskard/scanner/performance/performance_bias_detector.py, giskard/visualization/templates/scan_report/html/_issue.html, tests/scan/test_performance_bias_detector.py
Added Fisher's exact test and permutation test for slice metrics significance testing. Todo: unit tests.
=> [GSK-1279] Fisher's exact test and permutation test for slice metrics significance testing

.github/workflows/build-python.yml, giskard/ml_worker/websocket/listener.py, giskard/ml_worker/websocket/utils.py, giskard/models/base/model.py, giskard/models/cache/cache.py, tests/communications/test_websocket_actor_tests.py, tests/models/test_model_cache.py
- Only persist/read cache when explicitly asked
- Only load artifacts onces per test suite execution (model therefore share cache for a suite)
- For scan since only one model is loaded cache is also shared
=> [GSK-2378] Only persist/read cache when explicitly asked

giskard/commands/cli_hub.py
Fixed newline issue when reading env file
[GSK-2403](https://linear.app/giskard/issue/GSK-2403/starting-container-with-env-file-add-new-line-after-env-variables)
=> Fixed newline issue when reading env file

giskard/core/core.py, giskard/datasets/base/__init__.py, giskard/ml_worker/websocket/__init__.py, giskard/ml_worker/websocket/utils.py, tests/communications/fixtures/with_alias.json, tests/communications/test_dto_serialization.py, tests/core/test_core.py
Use object instead of string for documentation
[GSK-2329 (Available on Linear)](https://linear.app/giskard/issue/GSK-2329/add-validator-for-callabledto-doc-property-to-be-valid-format)
=> [GSK-2329] Use object instead of string for documentation

giskard/llm/evaluators/__init__.py, giskard/llm/evaluators/base.py, giskard/llm/evaluators/requirements.py, giskard/testing/tests/llm/__init__.py, giskard/testing/tests/llm/output_requirements.py, tests/llm/evaluators/test_llm_based_evaluators.py, tests/llm/evaluators/test_requirements_evaluator.py, tests/testing/test_llm_output_requirement.py
Added a LLM-as-judge per row evaluator
- [GSK-2300 (Available on Linear)](https://linear.app/giskard/issue/GSK-2300/llm-as-a-judge-row-wise-custom-requirement-test)
=> Added a LLM-as-judge per row evaluator

giskard/push/contribution.py
Fixed error from contribution push when model is text generation
[GSK-2321 (available on Linear)](https://linear.app/giskard/issue/GSK-2321/push-feature-error-no-attribute-keys)
=> Fixed error from contribution push when model is text generation

giskard/testing/tests/llm/injections.py, tests/scan/llm/test_prompt_injection_detector.py
Fixed the debugging issue by using the new debugging workflow
- [GSK-2470](https://linear.app/giskard/issue/GSK-2470/debugging-a-test-with-kwargs-doesnt-work)
=> GSK-2470 Debugging a test with kwargs doesn't work

giskard/client/dtos.py, giskard/client/giskard_client.py, giskard/core/core.py, giskard/core/suite.py, giskard/ml_worker/websocket/listener.py, giskard/ml_worker/websocket/utils.py, giskard/registry/giskard_test.py
Updated `Suite.upload()` method to upload modifications to existing suite
```python
import giskard
client = giskard.GiskardClient(
url="http://localhost:9000",  # URL of your Giskard instance
key="gsk-...")
suite = giskard.Suite.download(client, 'test', 52)
from giskard.testing.tests.data_quality import test_data_uniqueness
suite.add_test(test_data_uniqueness())
suite.upload(client, 'test')
```
```python
import giskard
client = giskard.GiskardClient(
url="http://localhost:9000",  # URL of your Giskard instance
key="gsk-...")
suite = giskard.Suite.download(client, 'test', 52)
suite.update_test_params(len(suite.tests) - 1, threshold=0.2) # Not ideal by index but will be changed in another PR
suite.upload(client, 'test')
```
```python
import giskard
client = giskard.GiskardClient( …
```
=> GSK-2545 Update `Suite.upload()` method to upload modifications to existing suite

tests/test_import_giskard.py
Add test to assert how long `import giskard` is running
Did local tests and took on average 3 seconds so put the threshold to 4, to confirm with runner output
=> GSK-2425 Add test to assert how long `import giskard` is running

giskard/models/base/model.py
Fixing issue when loading `BaseModel` instances (or custom model classes that directly extend `BaseModel`)
`model_id, meta = cls.read_meta_from_local_dir(local_dir)` returns a `Tuple[MetaModelInfo, ModelMeta]`, therefore, `model_id` is not a `str` as it should. 
@rabah-khalek this fix might interest you.
=> Fix BaseModel loading

.github/workflows/pre-commit-checks.yml, .pre-commit-config.yaml
Note : in addition, everyone should follow step 1 and 2 from https://docs.gitguardian.com/ggshield-docs/integrations/git-hooks/pre-commit#global-pre-commit-hook
=> Add ggshield to pre-commit

giskard/ml_worker/websocket/listener.py, tests/communications/test_websocket_actor_tests.py
This PR fixes a bug in which custom testing functions could not be run from the Hub.
[GSK-2626 (available on Linear)](https://linear.app/giskard/issue/GSK-2626/custom-uploaded-test-doesnt-run-on-catalog)
=> [GSK-2626] Fix run test action for custom tests

giskard/core/suite.py
The link has been changed following the frontend refactor.
[GSK-2659] URL fails due to new URL
=> [GSK-2659] Fix link in log after uploading a test suite

giskard/scanner/calibration/overconfidence_detector.py, giskard/scanner/calibration/underconfidence_detector.py
I updated `OverconfidenceDetector` and `UnderconfidenceDetector` to display `metric_value_perc` with 2 decimals.
#1730
=> Update calibration detectors to display `metric_value_perc` with 2 decimals

giskard/core/test_result.py
In order to allow test to not show metrics by simply doing `TestResult(passed=True)` instead of `TestResult(passed=True, metric=None)`
=> GSK-2407 Made metric None as default

giskard/cli_utils.py, giskard/commands/cli_hub.py, giskard/commands/cli_worker.py, giskard/ml_worker/ml_worker.py, giskard/ml_worker/stomp/client.py, giskard/ml_worker/websocket/__init__.py, giskard/ml_worker/websocket/listener.py, giskard/settings.py, pyproject.toml, tests/communications/fixtures/with_alias.json, tests/communications/test_dto_serialization.py, tests/communications/test_websocket_actor.py, tests/stomp/test_ml_worker.py, tests/utils.py
See also https://github.com/Giskard-AI/giskard-hub/pull/399
TODO:
- [ ] re word the error message in cli worker
=> [GSK-2497] Allow to connect multiple external mlworkers

giskard/scanner/robustness/text_transformations.py, giskard/scanner/scanner.py
TextNumberToWordTransformation was failing if row["language__gsk__meta"] was nan 
Before : https://github.com/Giskard-AI/giskard/actions/runs/7750039265
After : https://github.com/Giskard-AI/giskard/actions/runs/7753720227
=> Fix tests run on enron

CONTRIBUTING.md
Updated the style guide section of `CONTRIBUTING.md` with the current code styling policy.
=> Update the contributing style guide

docs/giskard_hub/write_and_debug_tests/index.md, docs/integrations/pytest/index.md, docs/open_source/scan/scan_llm/index.md
=> [GSK-2775] Fix typos in docs

docs/conf.py
Docs now use the `stable` version by default, but our links to notebook only mapped version `latest` to branch `main`.
Temporary fix while we understand how to link to the released tag.
=> Temporary fix for docs links to notebooks

giskard/visualization/templates/scan_report/markdown/huggingface.md
Previously, we removed the transformation column, which was not what we want. Because it is not obvious in the description. This PR hides the columns (data slice, transformation) **only** when they are empty.
Test: locally tested with Titanic
Demo: the scan report template posted [here](https://huggingface.co/spaces/ZeroCommand/test-giskard-evaluator/discussions/13)
=> [GSK-2270] Add the transformation column back & hide it only if not used

.github/workflows/create-release.yml
In order to only have the light theme logo display in PyPI, we simply remove the dark theme logo `img` tag from the README as we build the release candidate wheel (which eventually gets published to PyPI in the current release flow).
(Assuming PyPI looks in the wheel rather than the tarball when fetching the package's description. Otherwise, we would rather make the edit in `post-release.yml`).
=> [GSK-2834] Show only light theme logo in PyPI package description

giskard/registry/utils.py, tests/models/test_model_serialization.py
By default we try to serialise models by value using cloudpickle in order to be able to execute them in ML Worker without having to install the referenced dependency. However cloudpickle is not able to serialise everything causing the serialisation to fail.
For complex code that aren't pickable, it's always possible to save the code in a module and install it into the ML worker. Therefore when cloudpickle fail to save objects by value, we fallback into saving by reference with a warning.  
- [GSK-2819 (Available on Linear)](https://linear.app/giskard/issue/GSK-2819/pydantic-models-cannot-be-serialised-with-our-code)
=> GSK-2819 Pydantic models cannot be serialised with our code

giskard/cli_utils.py, giskard/commands/cli_worker.py, giskard/scanner/scanner.py, giskard/utils/logging_utils.py, tests/test_worker_pool.py, tests/utils/test_logging_utils.py
Updated logger to only update giskard log level to INFO by default
- [GSK-2822 (Available on Linear)](https://linear.app/giskard/issue/GSK-2822/dont-edit-global-logger-level)
=> GSK-2822 Don't edit global logger level

giskard/scanner/robustness/text_transformations.py, tests/scan/test_text_transformations.py
=> [GSK-2871] Fix TextPerturbationDetector failed with error from `num2word` under "it" or "fa" language code

giskard/core/suite.py, giskard/datasets/base/__init__.py, giskard/scanner/report.py
Fix quality badge using https://peps.python.org/pep-0563/ for bug due to self annotation
=>     GSK-2874 Fix quality badge using https://peps.python.org/pep-0563/

giskard/llm/client/base.py, giskard/llm/client/openai.py, giskard/llm/evaluators/base.py, giskard/llm/evaluators/coherency.py, giskard/llm/evaluators/correctness.py, giskard/llm/generators/base.py, giskard/llm/generators/sycophancy.py, giskard/llm/testcase.py, giskard/llm/utils.py, giskard/scanner/llm/base.py, giskard/scanner/llm/llm_faithfulness_detector.py, giskard/scanner/llm/llm_output_formatting_detector.py, giskard/testing/tests/llm/correctness.py, giskard/testing/tests/llm/ground_truth.py, giskard/testing/tests/llm/hallucination.py, giskard/testing/tests/llm/output_requirements.py, tests/testing/test_llm_output_requirement.py
Added `rng_seed` param to evaluators, generators and tests using LLM in. order to ensure reproducibility. 
- [GSK-2376 (Available on Linear)](https://linear.app/giskard/issue/GSK-2376/add-seed-to-llm-generators-and-evaluators-in-order-to-ensure)
=> GSK-2376 Add seed to LLM generators and evaluators in order to ensure reproducibility

giskard/scanner/robustness/text_transformations.py
During the scan, I found failed Robustness detector for some models with some datasets.
The reason is that `num2words` does not implement all languages, it could raise `NotImplementedError`. In this case, the lib recommends to have a fallback to English.
[GSK-2920] TextPerturbationDetector failed with error: 'NotImplementedError'
=> [GSK-2920] Fallback to english if `num2words` does not implement in a language

.github/workflows/build-python.yml, giskard/__init__.py, giskard/utils/sentry.py, pdm.lock, pyproject.toml
Added Sentry integration in order to receive exception reports.
Only information coming from `giskard`, `pandas` and `numpy` are being sent
=> GSK-1807 Integrate Sentry

docs/community/contribution_guidelines/index.rst
Fix testing links in contribution guideline from ML Worker.
=> [GSK-2937] Update docs after moving non-ML worker code outside

docs/reference/notebooks/wage_classification.ipynb, giskard/datasets/base/__init__.py
The notebook wage classification was wrongly named german credit scoring
=> GSK-2604 GSK-2766 Renamed tittle of wage classification notebook

giskard/llm/evaluators/string_matcher.py, giskard/testing/tests/llm/injections.py
=> [GSK-3303] Fix validation issue with tuple, also fixes param names

giskard/llm/client/__init__.py
=> Fix the llm client to reset when changing llm api or model

giskard/testing/tests/llm/injections.py
=> Prevent torch faulty version on MacOS

.github/workflows/build-python.yml, pdm.lock, pyproject.toml
=> Update lockfile & clear runner disk

giskard/client/giskard_client.py
This PR adds telemetry to the new methods regarding Multi ML Worker implemented in `GiskardClient`.
[GSK-3419 (available on Linear)](https://linear.app/giskard/issue/GSK-3419/add-mixpanel-telemetry)
=> [GSK-3419] Add mixpanel telemetry to new client methods 

giskard/client/giskard_client.py, giskard/client/python_utils.py
Extract extra package information using `importlib_meta`:
- allows to set `exact_deps` in `initialize_kernel` to take all extra package information (but it could fail on managed side)
- otherwise, we just add for our "giskard"
The output should be:
```
giskard[hub, llm]==2.8.0
```
modified)
=> [GSK-3430] Check if we can detect the version of giskard library

giskard/client/giskard_client.py, giskard/utils/environment_detector.py
Only install giskard and prompt user to complete the dependency list
modified)
=> [GSK-3442] Install giskard only on google colab

giskard/rag/knowledge_base_plots.py, giskard/rag/report.py, giskard/visualization/templates/rag_report/rag_report.html, giskard/visualization/templates/rag_report/static/style.css
=> Raget redesign

docs/open_source/scan/scan_llm/index.md, giskard/llm/client/bedrock.py, giskard/llm/embeddings/bedrock.py, pdm.lock, pyproject.toml, tests/llm/test_llm_client.py
As the Claude models become more popular, it is helpful to provide native support for these models in an AWS environment. This feature adds native support for using an LLM client with Amazon Bedrock. As a first step, it supports the Claude 3 family of text generation models as well as the Titan text embedding models. Having implemented this myself, I have seen the QA sets produced by Haiku to be a great blend of speed and useful for a very low cost. 
Here is how I envision this feature being used in the current library's implementation. This follows the test set generation example [here](https://docs.giskard.ai/en/latest/open_source/testset_generation/testset_generation/index.html).
```python
import os
import boto3
import pandas as pd
import giskard
from giskard.llm.client.bedrock import …
```
=> [GSK-1590] native support for claude 3 and titan embeddings on Bedrock

.github/workflows/build-python.yml, pyproject.toml
Fixed dependencies installation on macos build by using fixing macos-12.
To fix the installation on macos-14 (arm64), we would require to have two different groups: https://github.com/pdm-project/pdm/issues/2189#issuecomment-1682455896 
modified)
=> Fixed dependencies installation on macos

giskard/llm/client/bedrock.py
Currently, system prompt are extracted by taking the first message (if it is from `user` and second message is also from `user`). Furthermore, `system` role are being changed to `user`, but only after trying to extract the system prompt creating inconsistencies.
This is not clear and create bug when using `giskard.rag.generate_testset` (system followed by user is translated to two user messages which is forbidden by the bedrock client):
```
2024-05-14 09:16:03,949 pid:43435 MainThread giskard.rag  ERROR    An error occurred (ValidationException) when calling the InvokeModel operation: messages: roles must alternate between "user" and "assistant", but found multiple "user" roles in a row
Traceback (most recent call last):
File "/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packa …
```
=> Fixed system prompt extraction inside of the bedrock client

giskard/llm/client/bedrock.py
Group message by role when using Claude bedrock client, this allow some edge case to work such as:
```python
resp = claude_client.complete(messages=[
ChatMessage(role='system', content='This is a test'),
ChatMessage(role='user', content='This is the first message'),
ChatMessage(role='user', content='This is the second message'),
ChatMessage(role='user', content='Is it working?'),
])
```
=> Group message by role when using claude bedrock client

package-lock.json, package.json, pdm.lock, pyproject.toml, tests/llm/test_llm_client.py
- Update dependencies to Pandas >=2.x 
- Restrict torch version to not include the latest ones that doesn't support macos x86_64
- Update gulp to a version that doesn't include any vulnerabilities 
https://github.com/Giskard-AI/giskard/issues/1476
=> Update dependencies to Pandas 2.X

giskard/llm/client/gemini.py
The [generate_content](https://ai.google.dev/api/python/google/generativeai/GenerativeModel#generate_content) method does not support seed on the [GenerationConfig](https://ai.google.dev/api/python/google/generativeai/types/GenerationConfig) param
#1901
=> Fix seed not supported by gemini

giskard/core/savable.py, giskard/core/suite.py, giskard/registry/giskard_test.py, tests/test_suite.py
Added a method to save and load a test suite inside a local folder:
``` python
suite = ...
suite.save('./my_suite')
loaded_suite = Suite.load('./my_suite')
```
modified)
=> Save a suite locally

giskard/registry/slicing_function.py, giskard/registry/transformation_function.py, tests/test_data_processing_pipeline.py
Following code wasn't working as expected:
```python
@slicing_function(name="slice cell level", cell_level=True)
def filter_cell_level_by(amount: int, min_value: int) -> bool:
return amount >= min_value
df = pd.DataFrame({"quantity": [1, 2, 3, 5, 7, 11, 13]})
dataset = Dataset(df, cat_columns=[])
min_five = filter_cell_level_by(min_value=5)
min_six = filter_cell_level_by(min_value=6)
dataset_greater_equals_five = dataset.slice(min_five, column_name="quantity")
dataset_greater_equals_six = dataset.slice(min_six, column_name="quantity")
assert list(dataset_greater_equals_five.df["quantity"]) == [5, 7, 11, 13]
assert list(dataset_greater_equals_six.df["quantity"]) == [7, 11, 13]
```
- `dataset_greater_equals_five` contains values where `quantity >= 5`
- `dataset_greater_equals_six` contains …
=> Fixed issue with slicing function and transformation function instances being shared

giskard/utils/logging_utils.py, giskard/utils/sentry.py
Fixed an issue making `import giskard` throwing a `ConnectionError` when network access is not available.
Furthermore made Sentry reporting an opt-in: `DISABLE_SENTRY_ENV_VARIABLE_NAME=False`
N/A
=> Disable sentry by default and handle connection error when network is not available

giskard/scanner/__init__.py, giskard/scanner/scanner.py, pdm.lock, pyproject.toml
=> Add max_issues_per_detector as parameter inside the scanner

giskard/scanner/llm/llm_basic_sycophancy_detector.py, giskard/scanner/llm/llm_harmful_content_detector.py, giskard/scanner/llm/llm_implausible_output_detector.py, giskard/scanner/llm/llm_information_disclosure_detector.py, giskard/scanner/llm/llm_output_formatting_detector.py, giskard/scanner/llm/llm_stereotypes_detector.py
This PR removes the disclaimer about GPT4 dependency on LLM detectors, since now the LLM detectors are compatible with any LLM client/model.
[GSK-3667 (available on Linear)](https://linear.app/giskard/issue/GSK-3667/remove-disclaimer-about-gpt4-dependency)
=> [GSK-3667] Remove disclaimer about GPT4 dependency on LLM detectors

giskard/rag/question_generators/base.py
This PR fixes incorrect temperature usage in the `_llm_complete` method of the `_LLMBasedQuestionGenerator` class as described in the related issue. It replaces the hardcoded temperature value of 0.5 with `self._llm_temperature`.
#1998 
modified)
=> Fix incorrect temperature usage in `_LLMBasedQuestionGenerator`

.github/ISSUE_TEMPLATE/giskard_bug_template.yaml
Removed the "Giskard hub version" input from the bug template since this is not relevant anymore
Removed hub version input from the bug template
=> Removed hub version input from the bug template

giskard/llm/client/mistral.py, pdm.lock, pyproject.toml, tests/llm/test_llm_client.py
Upgraded `mistralai` dep to >= 1
=> Upgraded `mistralai` dep to >= 1

tests/test_import_giskard.py
=> Fixed randomly failing tests

tests/test_import_giskard.py
=> Increased threshold of import time

pyproject.toml
Bokeh >= 3.6 cause issue with rendering plots when saving to html file
Run this code
```python
import os
import giskard
from giskard.llm.client.openai import OpenAIClient
os.environ["OPENAI_API_KEY"] = "sk-..."
giskard.llm.set_llm_api("openai")
oc = OpenAIClient(model="gpt-4-turbo-preview")
giskard.llm.set_default_client(oc)
import pandas as pd
from giskard.rag import KnowledgeBase, generate_testset
df = pd.read_csv("knowledge_base.csv")
knowledge_base = KnowledgeBase.from_pandas(df, columns=["q", "a"])
testset = generate_testset(
knowledge_base,
num_questions=10,
language='en',  # optional, we'll auto detect if not provided
agent_description="A customer support chatbot for company X", # helps generating better questions
)
testset.save("my_testset.jsonl")
from giskard.rag import QATestset …
```
=> Fixed issue of RAG results plots rendering

.github/workflows/build-python.yml, .github/workflows/retry-workflow.yml
Added workflow to automatically rerun Python build on failure up to times
=> Added workflow to automatically rerun Python build on failure up to times

giskard/rag/question_generators/complex_questions.py
=> Correct prompt Up to -> More than

giskard/rag/report.py, giskard/rag/testset.py, tests/rag/test_qa_testset.py
=> Add force_ascii=False when generating JSONL

giskard/rag/metrics/ragas_metrics.py
This PR fixes an import bug in which was making `giskard` not compatible with `ragas==0.2.2`.
#2051
=> [GSK-3881] Fix RAGAS compatibility

giskard/rag/report.py
Fixes #2057
Fixes #2057
modified)
=> Update report testset file extension

pdm.lock, pyproject.toml, tests/llm/test_llm_client.py, tests/models/test_model_serialization.py, tests/rag/test_ragas_metrics.py
This PR fixes a bug in which Mlflow-related tests were flaky (not deterministic). Basically, it updates the mlflow-skinny version to match the original mlflow version. This PR also upgrades dependencies and update tests to match the new dependencies version.
=> Limit mlflow-skinny version in ml_runtime

.github/workflows/build-python.yml, .github/workflows/create-release.yml, .github/workflows/lock-deps.yml, giskard/testing/tests/statistic.py
The boolean indexer of the `test_output_in_range` is mismatching the sliced dataset.
Since we want to keep the original indexes for debugging purpose, to solution was to reindex the  boolean indexer used as mask to the sliced dataset index
#2061
=> Fixed boolean indexer mismatching issue

docs/open_source/scan/scan_llm/index.md, docs/open_source/setting_up/index.md, docs/open_source/testset_generation/testset_generation/index.md
In the docs, there was a missing word (`openai`) when trying to call `set_embedding_model`.
This PR fixes the Azure/OpenAI docs, updating the code to call.
Linear card: [GSK-3941](https://linear.app/giskard/issue/GSK-3941/fix-azure-openai-client-setup-docs)
=> [GSK-3941] Fix Azure/OpenAI client setup docs

.github/workflows/create-release.yml
Fix `create-release.yml` workflow after upgrading `slack-github-action` to v2
=> Fix slack jobs in create-release GH action

docs/open_source/scan/scan_llm/index.md, docs/open_source/setting_up/index.md, docs/open_source/testset_generation/testset_generation/index.md
Sometimes `llama3.1` model doesn't generate JSON responses in a proper format. After doing some manual tests, we have seen that `qwen2.5` performs better on this task. Therefore, this PR updates the Ollama docs to showcase `qwen2.5` as model example instead of `llama3.1`.
=> chore(docs): replace llama3.1 with qwen2.5 on ollama docs

giskard/scanner/llm/llm_harmful_content_detector.py, giskard/scanner/llm/llm_stereotypes_detector.py
Some detectors are just returning a placeholder as description instead of the real description. This PR fixes the `get_issue_description` from these detectors to return the whole description.
Example:
- `LLMHarmfulContentDetector`
- `LLMStereotypesDetector`
[GSK-4238 (available on Linear)](https://linear.app/giskard/issue/GSK-4238/return-right-description-for-get-issue-description-in-requirement)
=> fix: Requirement Based Detectors to return right description

pdm.lock, pyproject.toml
Upgraded the litellm requirement in pyproject.toml
#2123
modified)
All tests passed
=> upgrade litellm version in pyproject.toml

docs/open_source/testset_generation/rag_evaluation/index.md
Documentation on how to implement custom metrics with raget.
https://github.com/Giskard-AI/giskard/issues/2140
modified)
=> chore(docs): update how to create custom metrics

.github/workflows/create-release.yml, .github/workflows/lock-deps.yml, package-lock.json, package.json
Batch of upgrades (NPM and GH workflows) - April 2025
#2135
#2136 
#2137 
#2138
=> chore(deps): batch upgrade 2025-04

giskard/core/core.py, pdm.lock, pyproject.toml
Grifffe was causing issue with openai in the notebook for deeplearning.ai
Fixes #2174 
modified)
=> chore(deps): update `griffe` version constraint to `>=1.0.0,<2.0.0`

giskard/rag/metrics/ragas_metrics.py
Implement abstract methods aembed_query and aembed_documents for `RagasEmbeddingsWrapper`. These methods are required because the `RagasEmbeddingsWrapper` inherits from the `BaseRagasEmbeddings` class which has these abstract methods.
This PR is related to [issue number 2177](https://github.com/Giskard-AI/giskard/issues/2177).
modified)
=> implement abstract methods for RagasEmbeddingsWrapper
